### ISSUE TITLE
 Embed the player in a layout

### ISSUE THREAD

**Issue by dtully** [ghondar/react-native-giraffe-player#2]
Hi there,
I have been trying to embed the player in a layout but I can't seem to figure out how. Have you ever done that? Can you give me any tips? I think your player is great and I really want to use it but I need to embed it. Thanks for your time! Danielle

**Comment by ghondar** [comment]
all the interface is made from xml and it can't embed in a react-native layout component, but you can have options as https://github.com/react-native-community/react-native-video
