### ISSUE TITLE
getCurrentPosition

### ISSUE THREAD

**Issue by mohsen0071** [ghondar/react-native-giraffe-player#3]
Hi,

How to use getCurrentPosition()

thanks

**Comment by ghondar** [comment]
hello @mohsen0071 , What would be the use you give him?

**Comment by mohsen0071** [comment]
Thank you @ghondar 
I want get current position (get seconds of video) and store in database

**Comment by mohsen0071** [comment]
JWPlayer, which is a web player, has such function where we get the exact time of played video. We want to track to see user behavior while is playing videos.
It is some kind of interval function. As soon as a time frame or buffered chunk is played, this function will be fired.

**Comment by ghondar** [comment]
Sorry for the delay in responding, You can to do so using workers with [this library](https://github.com/fabriciovergal/react-native-workers). You must read the [observation](https://github.com/fabriciovergal/react-native-workers/blob/master/OBSERVATIONS.md) also.
I share you a [example](https://github.com/ghondar/react-native-giraffe-player-with-workers)

**Comment by mohsen0071** [comment]
Thanks for your response,
The problem has been resolved, but it doesn't work on Android version 5 and below

Regards

**Comment by mohsen0071** [comment]
Hello,
The mentioned version issue is now resolved. But there is another unsolved issue.
When I play the video for the first time, it shows the **current position**, as expected. But it is not shown on the 2nd or 3rd play.

**Comment by ghondar** [comment]
do you have some example that you can share?

**Comment by mohsen0071** [comment]
Thanks for your response,

**index.android.js** 

import React, { Component } from 'react'
import { ScrollView, Text, Image, View, TouchableOpacity, TouchableHighlight, AppState } from 'react-native'
import { Images } from '../Themes'

import { Worker } from 'rn-workers';

import GPlayer from 'react-native-giraffe-player'
// Styles
import styles from './Styles/LaunchScreenStyles'

export default class LaunchScreen extends Component {
  

  componentWillMount() {
    GPlayer.addEventListener('onRenderingStart', this.onRenderingStart);
    GPlayer.setTitle('hola mundo')
 
  }

  componentWillUnmount() {
    GPlayer.removeEventListener('onRenderingStart', this.onRenderingStart);
  }


  onRenderingStart() {

    GPlayer.getDuration()
      .then((data) => {
        console.log(data);
      })
      .catch((e) => {
        console.log(e);
      });
    // interval 1 sec to show current position - worker at index.worker.js
    this.worker = new Worker();
    this.worker.postMessage("start");
    this.worker.onmessage = async message => {
      console.log(message)
      if(message == 'position') {
        const position = await GPlayer.getCurrentPosition()
        console.log(position)
      }
    }
  }

  render() {
    return (
      <View style={styles.container}>

        <TouchableHighlight onPress={() => { GPlayer.play('https://58afd288af806.streamlock.net/faranesh/_definst_/mp4:232-how-to-make-video-tutorial-with-camtasia/4ca7d87e3bb0f9abe4fea8f9c01f27d9.mp4/manifest.m3u8'); }}>
          <Text>
            Play video 1
          </Text>
        </TouchableHighlight>

         <TouchableHighlight onPress={() => { GPlayer.play('https://58afd288af806.streamlock.net/faranesh/_definst_/mp4:16055-photoshop-cc-for-photographers/59070b0135a48-01.mp4/manifest.m3u8'); }}>
          <Text>
            Play video 2
          </Text>
        </TouchableHighlight>

      </View>
    )
  }
}


**index.worker.js**

import { WorkerService } from 'rn-workers';

const worker = new WorkerService();
/* get message from application. String only ! */
worker.onmessage = (message) => {
  if(message == 'start') {
    setInterval(() => {
      worker.postMessage('position');
    }, 1000)
  }
}

**Comment by mohsen0071** [comment]
Thank you

**Comment by ghondar** [comment]
really not is what happens, it seems as if the player prevented to run the setInterval again, is rare

**Comment by mohsen0071** [comment]
Assume that we have 2 videos in a page.
If I play the first one, the Interval runs as expected.
But when I play the next video, the interval doesn't run.

**Comment by ghondar** [comment]
hi @mohsen0071, forgot rn-workers, i couldn't resolve setInterval bug, I've tried [this library](https://github.com/ocetnik/react-native-background-timer) and and I think that I believe that it can work for what you want, check out my [latest commit](https://github.com/ghondar/react-native-giraffe-player-with-workers/commit/f3627f6be83244e1bcbf94449c7809d214b913a2)

**Comment by mohsen0071** [comment]
Dear Anthony,
My issue is solved. Than you very much.

**Comment by ghondar** [comment]
you are welcome
