### ISSUE TITLE
How to use setFullScreenOnly

### ISSUE THREAD

**Issue by xvonabur** [ghondar/react-native-giraffe-player#6]
Can you explain how to use `setFullScreenOnly` in README example? 
When do I need to call it?

**Comment by ghondar** [comment]
@xvonabur sure, [here](https://github.com/ghondar/react-native-giraffe-player/commit/02c4eab6388d43b7b64760b5403d04913ca7b5b8)

**Comment by xvonabur** [comment]
@ghondar , link is broken. Github returns 404

**Comment by ghondar** [comment]
@xvonabur updated

**Comment by xvonabur** [comment]
Thanks!
